name: efetack
favicon: null
layout_spectrum: 0.719216377241537
typography_spectrum: 0.4851064
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: This is the TITLE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fbfcfe'
    - '#000000'
    - '#717171'
    - '#6b96c0'
    - '#afb1b1'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
