name: efetack
favicon: null
layout_spectrum: 0.3106383
typography_spectrum: 0.5340425
author:
  url: 'http://efetak.de'
navigation:
  - name: See this
    id: 38f59484-c103-4fb7-be0a-6c8e17558baf
    type: content
  - name: my homepage
    url: 'http://www.efetack.com'
    type: external
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: WELCOME TO MY WORLD
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3e3838'
    - '#7f7a6f'
    - '#655b58'
    - '#0d0b0d'
    - '#d4d2d6'
  brandStrength: 0.4375
  lightness: 0.5234042
  saturation: 0.3021277
  rhythmicContrast: 0.6106383
purpose: []
