name: efetack
favicon: null
layout_spectrum: 0.719216377241537
typography_spectrum: 0.4851064
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: This is the TITLE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1783bb'
    - '#091518'
    - '#10f7ff'
    - '#12444c'
    - '#eaeaea'
  brandStrength: 0.6875
  lightness: 0.1875
  saturation: 0.07691581174731255
  rhythmicContrast: 0.5
purpose: []
